name: Update Exchange Rate Cache

on:
  schedule:
    - cron: "0 1 * * *" # 每天 01:00 UTC 运行（早于其他工作流）
  workflow_dispatch:

jobs:
  update-exchange-rate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Update exchange rate
        run: |
          # 更新USD到CNY汇率缓存
          npm run update:exchange

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 添加文件到暂存区
          git add public/exchange-rate.json
          
          # 检查是否有改动
          if git diff --staged --quiet; then
            echo "汇率没有变化，无需提交"
            exit 0
          fi
          
          # 尝试提交
          git commit -m "更新USD到CNY汇率缓存 [CI 自动]"
          
          # 重试推送机制（最多3次）
          for i in {1..3}; do
            echo "尝试推送 (第 $i 次)"
            if git push origin main; then
              echo "推送成功"
              exit 0
            else
              echo "推送失败，尝试重新同步"
              git pull --rebase origin main
              sleep 5
            fi
          done
          
          echo "推送失败，已重试3次"
          exit 1